receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      # process:
      processes:
      paging:
  docker_stats:
    collection_interval: 10s
    endpoint: unix:///var/run/docker.sock
  otlp:
    protocols:
      grpc:
        endpoint: :4317
        include_metadata: true
      # http:
      #   endpoint: :4318
        # tls:
        #   cert_file: /certs/server.crt
        #   key_file: /certs/server.key
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: 'traefik'
  #         scrape_interval: 5s
  #         static_configs:
  #           - targets: ['0.0.0.0:8082']

processors:
  batch:
    metadata_keys:
    - uptrace-dsn

  resourcedetection:
    detectors: [env, ec2, system]

exporters:
  otlp/uptrace-host:
    endpoint: uptrace.service.tvduc95.ovh:14317
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://srNWDSH8FG3Gur4hb4eU@uptrace.service.tvduc95.ovh:14318?grpc=14317' }

  otlp/uptrace-traefik:
    endpoint: uptrace.service.tvduc95.ovh:14317
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://eHHpqm844pc8PSH33bwH@uptrace.service.tvduc95.ovh:14318?grpc=14317' }

  otlp/uptrace:
    endpoint: uptrace.service.tvduc95.ovh:14317
    tls:
      insecure: true
    auth:
      authenticator: headers_setter

extensions:
  health_check:

  headers_setter:
    headers:
      - action: insert
        key: uptrace-dsn
        from_context: uptrace-dsn

service:
  extensions: [health_check, headers_setter]

  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/uptrace

    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/uptrace

    metrics/host:
      receivers:
        - hostmetrics
        - docker_stats
      processors:
        - batch
        - resourcedetection
      exporters:
        - otlp/uptrace-host

    # metrics/prometheus:
    #   receivers:
    #     - prometheus
    #   processors:
    #     - batch
    #   exporters:
    #     - otlp/uptrace-traefik

    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/uptrace