version: '3'

services:

  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8082:8082
    deploy:
      placement:
        constraints: 
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.docker.lbswarm=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - public_certificates:/certificates
      - /services-infra/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /services-infra/traefik/dynamic_config.yml:/etc/traefik/dynamic_config.yml
    networks:
      - public

volumes:
  public_certificates:

networks:
  public:
    external: true
