version: '3'

services:

  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.role == manager
    labels:
      - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - public_certificates:/certificates
      - /services-infra/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /services-infra/traefik/dynamic_config.yml:/etc/traefik/dynamic_config.yml
    networks:
      - public
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  public_certificates:

networks:
  public:
    external: true
