version: '3'

services:

  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints: 
          - node.role == manager
    labels:
        - traefik.enable=true
        - traefik.docker.network=public
        # - traefik.docker.lbswarm=true
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - public_certificates:/certificates
      - /services-infra/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /services-infra/traefik/dynamic_config.yml:/etc/traefik/dynamic_config.yml
    environment:
      - CF_API_EMAIL=tv.duc95@gmail.com
      - CF_DNS_API_TOKEN=TsrCMKBseUCNpkj9TpNi2gy48Bd4tLQ5AyDcuvYP
      - CF_ZONE_API_TOKEN=MwIi7Pn5NtG_3zdqZhXnIEud7f04HN21NT9XmY6j
    networks:
      - public
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  public_certificates:

networks:
  public:
    external: true
