http:

################################################################
# Routers configuration
################################################################

  routers:
    traefik-public:
      entrypoints: https
      rule: Host(`traefik.services.tvduc95.ovh`)
      service: api@internal
      middlewares: 
        - admin-auth

################################################################
# Middlewares configuration
################################################################

  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "admin:$2y$05$lyY5mTijBUzGbiicVMWDWOmqEZej2GAE2cf481RQqDhVBMDm2ZwKq"