################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  http:
    address: :80
    redirections:
        entryPoint:
          to: https
          permanent: true

  https:
    address: :443
    http:
      tls:
        certResolver: le
        # domains:
        # - main: "services.tvduc95.ovh"
        #   sans:
        #     - "*.services.tvduc95.ovh"

################################################################
# Traefik logs configuration
################################################################

log: {}
  # level: DEBUG
accessLog: {}

################################################################
# API and dashboard configuration
################################################################

api: {}

################################################################
# Docker configuration backend
################################################################

providers:
  # Enable Docker configuration backend
  docker:
    exposedByDefault: false
    swarmMode: true
    network: public
    defaultRule: "HOST(`{{ normalize .Name }}.services.tvduc95.ovh`))"

  file:
    filename: /etc/traefik/dynamic_config.yml

################################################################
# Certificate configuration
################################################################

certificatesResolvers:
  le:
    acme:
      email: tvduc95@gmail.com
      storage: /certificates/acme.json
      tlsChallenge: {}
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # dnsChallenge:
      #   provider: cloudflare

