################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          permanent: true

  https:
    address: :443
    http:
      tls:
        certResolver: le
        # domains:
        # - main: "service.tvduc95.ovh"
        #   sans:
        #     - "*.service.tvduc95.ovh"

  # metrics:
  #   address: :8082
    

################################################################
# Traefik logs configuration
################################################################

log: {}
  # level: DEBUG
# accessLog: {}

# metrics:
#   prometheus:
#     entryPoint: metrics
#     addEntryPointsLabels: true
#     addRoutersLabels: true
#     addServicesLabels: true

metrics:
  otlp:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    grpc:
      endpoint: host.docker.internal:4317
      insecure: true
      headers:
        UPTRACE_DSN: http://eHHpqm844pc8PSH33bwH@uptrace.service.tvduc95.ovh:14318?grpc=14317

tracing:
  otlp:
    grpc:
      endpoint: host.docker.internal:4317
      insecure: true
      headers:
        UPTRACE_DSN: http://eHHpqm844pc8PSH33bwH@uptrace.service.tvduc95.ovh:14318?grpc=14317

################################################################
# API and dashboard configuration
################################################################

api: {}

################################################################
# Docker configuration backend
################################################################

providers:
  # Enable Docker configuration backend
  swarm:
    exposedByDefault: false
    network: public
    defaultRule: "HOST(`{{ normalize .Name }}.service.tvduc95.ovh`))"

  file:
    filename: /etc/traefik/dynamic_config.yml
    watch: true

################################################################
# Certificate configuration
################################################################

certificatesResolvers:
  le:
    acme:
      email: tvduc95@gmail.com
      storage: /certificates/acme.json
      tlsChallenge: {}
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # dnsChallenge:
      #   provider: cloudflare

