version: '3'

services:
  api:
    image: tvduc95/testapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - public
      - default
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.http.routers.testapi.rule=Host(`testapi.service.tvduc95.ovh`)
        - traefik.http.routers.testapi.entrypoints=https
        - traefik.http.routers.testapi.service=testapi
        - traefik.http.services.testapi.loadbalancer.server.port=8080

networks:
  public:
    external: true
  default:
