version: '3'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - data:/data
    networks:
      - public
      - agent_network
    ports:
      - 9000:9000
      - 9443:9443
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.services.tvduc95.ovh`)
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.routers.portainer.service=portainer
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        # Edge
        - traefik.http.routers.portaineredge.rule=Host(`portaineredge.services.tvduc95.ovh`)
        - traefik.http.routers.portaineredge.entrypoints=https
        - traefik.http.routers.portaineredge.service=portaineredge
        - traefik.http.services.portaineredge.loadbalancer.server.port=8000

volumes:
  data:

networks:
  public:
    external: true
  agent_network:
    external: true
